title: Anegada Theatre
email: info@anegadatheatre.org.uk
description: >- 
  ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: 
github_username:  samozzy
logo_path: "/static/img/logo.png"
logo_path_footer: "/static/img/logo_footer.png"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

strict_front_matter: true 
livereload: true 

plugins:
  - bootstrap 
  - jekyll-paginate

sass:
    sass_dir: _sass
    style: expanded 
    load_paths:
      - _sass 
      - vendor/bundle/ruby/*/gems/bootstrap*/assets/stylesheets/

collections:
  content:
    output: true
    permalink: :path/
  shows:
    output: true 
    permalink: /shows/:path/
  blog:
    output: true 
    permalink: /blog/:year/:month/:slug/
permalink: pretty 

defaults:
  # Defaults for pages
  - scope:
      type: content
    values:
      layout: default
  - scope: 
      type: blog 
    values:
      layout: blog-post 
