title: Anegada Theatre
email: info@anegadatheatre.org.uk
description: >- 
  "Based in the East Midlands, we strive to make art that is diverse and will spark conversation. Through adaptations that reframe traditional literature and original productions that experiment with poetry, drama and visual media, we aim to create theatre that is unique and challenges our audiences."
baseurl: ""
url: "https://anegadatheatre.org.uk/"
twitter_username: anegadatheatre
github_username:  samozzy
logo_path: "/static/img/logo.png"
logo_path_footer: "/static/img/logo_footer.png"
timezone: Europe/London

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

strict_front_matter: true 
livereload: true 

plugins:
  - bootstrap 
  - jekyll-paginate

sass:
    sass_dir: _sass
    style: expanded 
    load_paths:
      - _sass 
      - vendor/bundle/ruby/*/gems/bootstrap*/assets/stylesheets/
      - /opt/build/cache/bundle/ruby/*/gems/bootstrap*/assets/stylesheets/

collections:
  content:
    output: true
    permalink: /:path/
  shows:
    output: true 
    permalink: /productions/:path/
    # Shows should be listed in folders according to their production
  productions:
    output: true 
    permalink: /productions/:path/
  blog:
    output: true 
    permalink: /blog/:year/:month/:slug/
permalink: pretty 

defaults:
  # Defaults for pages
  - scope:
      type: content
    values:
      layout: default
  - scope: 
      type: blog 
    values:
      layout: blog-post 
  - scope: 
      type: productions
    values:
      layout: production
  - scope: 
      type: shows
    values: 
      layout: production
