name: Build to GitHub pages

on:
  schedule:
    - cron: '30 17-20 * * *'
  push:
    branches:
      - master
  pull_request:
    branches:
      - master 
  workflow_dispatch:
    branches:
      - main

jobs:
  jekyll:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    # Use GitHub Actions' cache to shorten build times and decrease load on servers
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    ### RUBY ###
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.0
    - name: Cache Ruby gems
      id: cache-gems
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-1-${{ hashFiles('Gemfile.lock') }}
    - name: Set Ruby gems directory
      run: bundle config path vendor/bundle && bundle config set --local deployment 'true'
    - name: Install Ruby gems
      run: bundle install --jobs 4 --retry 3

    ### BUILD ###
    - name: Build Jekyll 
      run: bundle exec jekyll build --verbose

    ### DEPLOY ###
    - name: Publish to GH Pages 🚀
      if: ${{ github.event_name == 'push' || github.event_name == 'schedule' && github.ref == 'refs/heads/master' }}
      uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: _site # The folder the action should deploy.
        CLEAN: true # Automatically remove deleted files from the deploy branch
